spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beautypattern?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.116.128
    port: 6379
    password: 123456

mybatis-plus:
  type-enums-package: org.geekbang.time.beautypatterninspring.ienum

server:
  port: 8080
